name: Build KMP Wasm and Deploy Next.js to Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


permissions:
  contents: read  # Required to fetch the repository content
  pages: write    # Allow deployment to GitHub Pages
  id-token: write # Required by actions/configure-pages

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job builds the Kotlin and Next.js projects and prepares the artifact for deployment
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: TofuDrivenDev/kmp-monorepo
          ref: web
          token: ${{ secrets.KMP_MONOREPO_PAT }}


      # --- KOTLIN/WASM BUILD STEPS ---
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      # 3. Set up Gradle
      - name: "⚙️ Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.12.1

      - name: Build Kotlin/Wasm Distribution
        run: gradle :appSandbox:wasmJsBrowserDistribution -DGITHUB_PAT=${{ github.token }}
        
      # # --- NEXT.JS BUILD STEPS ---
      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20

      - name: Clean and recreate Wasm directory
        run: |
          rm -rf appComposeByExample/web/public/wasm
          mkdir -p appComposeByExample/web/public/wasm

      - name: Copy Wasm build output to Next.js public folder
        run: cp ./appSandbox/build/dist/wasmJs/productionExecutable/*.js ./appSandbox/build/dist/wasmJs/productionExecutable/*.wasm ./appComposeByExample/web/public/wasm/

      # - name: Setup Node.js Cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      - name: Install Next.js dependencies
        # Use a working directory to run commands for the Next.js app
        working-directory: ./appComposeByExample/web
        run: npm ci

      - name: Build Next.js project for static export
        working-directory: ./appComposeByExample/web
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the static output from the Next.js build
          path: ./appComposeByExample/web/out

      # 7. Deploy to GitHub Pages
      - name: "🚀 Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
        
